// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/health.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_health_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RamUsage         float64                `protobuf:"fixed64,1,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	DiskUsage        float64                `protobuf:"fixed64,2,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	CpuPercentage    []float64              `protobuf:"fixed64,3,rep,packed,name=cpu_percentage,json=cpuPercentage,proto3" json:"cpu_percentage,omitempty"`
	CpuPercentageAvg float64                `protobuf:"fixed64,4,opt,name=cpu_percentage_avg,json=cpuPercentageAvg,proto3" json:"cpu_percentage_avg,omitempty"`
	NetworkBytesRecv uint64                 `protobuf:"varint,5,opt,name=network_bytes_recv,json=networkBytesRecv,proto3" json:"network_bytes_recv,omitempty"`
	NetworkBytesSent uint64                 `protobuf:"varint,6,opt,name=network_bytes_sent,json=networkBytesSent,proto3" json:"network_bytes_sent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetRamUsage() float64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *HealthResponse) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *HealthResponse) GetCpuPercentage() []float64 {
	if x != nil {
		return x.CpuPercentage
	}
	return nil
}

func (x *HealthResponse) GetCpuPercentageAvg() float64 {
	if x != nil {
		return x.CpuPercentageAvg
	}
	return 0
}

func (x *HealthResponse) GetNetworkBytesRecv() uint64 {
	if x != nil {
		return x.NetworkBytesRecv
	}
	return 0
}

func (x *HealthResponse) GetNetworkBytesSent() uint64 {
	if x != nil {
		return x.NetworkBytesSent
	}
	return 0
}

var File_proto_health_proto protoreflect.FileDescriptor

const file_proto_health_proto_rawDesc = "" +
	"\n" +
	"\x12proto/health.proto\x12\x06health\"\x0f\n" +
	"\rHealthRequest\"\xfd\x01\n" +
	"\x0eHealthResponse\x12\x1b\n" +
	"\tram_usage\x18\x01 \x01(\x01R\bramUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x02 \x01(\x01R\tdiskUsage\x12%\n" +
	"\x0ecpu_percentage\x18\x03 \x03(\x01R\rcpuPercentage\x12,\n" +
	"\x12cpu_percentage_avg\x18\x04 \x01(\x01R\x10cpuPercentageAvg\x12,\n" +
	"\x12network_bytes_recv\x18\x05 \x01(\x04R\x10networkBytesRecv\x12,\n" +
	"\x12network_bytes_sent\x18\x06 \x01(\x04R\x10networkBytesSent2F\n" +
	"\x06Health\x12<\n" +
	"\tGetHealth\x12\x15.health.HealthRequest\x1a\x16.health.HealthResponse\"\x00B*Z(github.com/noahkw/gohealthi/proto/healthb\x06proto3"

var (
	file_proto_health_proto_rawDescOnce sync.Once
	file_proto_health_proto_rawDescData []byte
)

func file_proto_health_proto_rawDescGZIP() []byte {
	file_proto_health_proto_rawDescOnce.Do(func() {
		file_proto_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_health_proto_rawDesc), len(file_proto_health_proto_rawDesc)))
	})
	return file_proto_health_proto_rawDescData
}

var file_proto_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_health_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: health.HealthRequest
	(*HealthResponse)(nil), // 1: health.HealthResponse
}
var file_proto_health_proto_depIdxs = []int32{
	0, // 0: health.Health.GetHealth:input_type -> health.HealthRequest
	1, // 1: health.Health.GetHealth:output_type -> health.HealthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_health_proto_init() }
func file_proto_health_proto_init() {
	if File_proto_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_health_proto_rawDesc), len(file_proto_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_health_proto_goTypes,
		DependencyIndexes: file_proto_health_proto_depIdxs,
		MessageInfos:      file_proto_health_proto_msgTypes,
	}.Build()
	File_proto_health_proto = out.File
	file_proto_health_proto_goTypes = nil
	file_proto_health_proto_depIdxs = nil
}
